# SPDX-License-Identifier: MIT
# For license details, see the repository root LICENSE file.
---
name: Security - Dependency Review

'on':
  pull_request:
    branches: [main]
  merge_group:

permissions: {}

concurrency:
  group: dependency-review-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dependency-review:
    # yamllint disable-line rule:line-length
    uses: lgtm-hq/lgtm-ci/.github/workflows/reusable-dependency-review.yml@f469f4d5c187f0700ccec4c023152fb68ee3dc89 # v0.32.3
    with:
      fail-on-severity: high
      tooling-ref: 'f469f4d5c187f0700ccec4c023152fb68ee3dc89' # v0.32.3
      egress-policy: block
      egress-preset: scorecard
      allowed-endpoints-mode: append
      allowed-endpoints: >
        api.deps.dev:443
        release-assets.githubusercontent.com:443
    permissions:
      contents: read
      pull-requests: read
