# SPDX-License-Identifier: MIT
# For license details, see the repository root LICENSE file.
---
name: PR - Auto Assign

'on':
  pull_request_target:
    types: [opened]

permissions: {}

jobs:
  assign:
    # yamllint disable-line rule:line-length
    uses: lgtm-hq/lgtm-ci/.github/workflows/reusable-pr-auto-assign.yml@66cad82ead0e5d119928c895c7d7da9c837989e5 # v0.52.3
    with:
      codeowners-path: .github/CODEOWNERS
      tooling-ref: '66cad82ead0e5d119928c895c7d7da9c837989e5' # v0.52.3
      egress-policy: block
      egress-preset: github-tooling
    permissions:
      contents: read
      pull-requests: write
