# SPDX-License-Identifier: MIT
# For license details, see the repository root LICENSE file.
---
name: PR - Auto Label

'on':
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions: {}

jobs:
  label:
    # yamllint disable-line rule:line-length
    uses: lgtm-hq/lgtm-ci/.github/workflows/reusable-pr-labeler.yml@f469f4d5c187f0700ccec4c023152fb68ee3dc89 # v0.32.3
    with:
      configuration-path: .github/labeler.yml
      sync-labels: false
      tooling-ref: 'f469f4d5c187f0700ccec4c023152fb68ee3dc89' # v0.32.3
      egress-policy: block
      egress-preset: github-tooling
    permissions:
      contents: read
      pull-requests: write
