# SPDX-License-Identifier: MIT
---
name: CI - Quality

'on':
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, ready_for_review]
  merge_group:
  workflow_dispatch:

permissions: {}

concurrency:
  group: quality-ci-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  quality:
    # yamllint disable-line rule:line-length
    uses: lgtm-hq/lgtm-ci/.github/workflows/reusable-quality-lint.yml@f469f4d5c187f0700ccec4c023152fb68ee3dc89 # v0.32.3
    permissions:
      contents: read
      packages: read
    with:
      tooling-ref: 'f469f4d5c187f0700ccec4c023152fb68ee3dc89' # v0.32.3
      egress-policy: block
      egress-preset: quality

  publish-quality-summary:
    needs: quality
    if: >-
      !cancelled()
      && github.event_name == 'pull_request'
      && github.event.pull_request.head.repo.full_name == github.repository
      && (
        github.event.pull_request.draft == false
        || github.event.action == 'ready_for_review'
      )
    # yamllint disable-line rule:line-length
    uses: lgtm-hq/lgtm-ci/.github/workflows/reusable-publish-quality-summary.yml@f469f4d5c187f0700ccec4c023152fb68ee3dc89 # v0.32.3
    permissions:
      contents: read
      pull-requests: write
    with:
      exit-code: ${{ needs.quality.outputs.exit-code }}
      tooling-ref: 'f469f4d5c187f0700ccec4c023152fb68ee3dc89' # v0.32.3
