# SPDX-License-Identifier: MIT
# For license details, see the repository root LICENSE file.
---
name: Release - Auto Tag

'on':
  push:
    branches: [main]
  workflow_dispatch:

permissions: {}

concurrency:
  group: release-auto-tag-${{ github.repository }}
  cancel-in-progress: false

jobs:
  auto-tag:
    # yamllint disable-line rule:line-length
    uses: lgtm-hq/lgtm-ci/.github/workflows/reusable-release-auto-tag.yml@43325346d688be984d6bde155603d18fbdd89278 # v0.33.0
    with:
      create-release: false
      tooling-ref: '43325346d688be984d6bde155603d18fbdd89278' # v0.33.0
      egress-policy: block
      egress-preset: github-tooling
    secrets:
      RELEASE_APP_ID: ${{ secrets.RELEASE_APP_ID }}
      RELEASE_APP_PRIVATE_KEY: ${{ secrets.RELEASE_APP_PRIVATE_KEY }}
    permissions:
      # write: create version tags on the repository
      contents: write
