# SPDX-License-Identifier: MIT
# For license details, see the repository root LICENSE file.
---
name: Release - Version PR

'on':
  push:
    branches: [main]
  workflow_dispatch:

permissions: {}

concurrency:
  group: release-version-pr-${{ github.repository }}
  cancel-in-progress: false

jobs:
  version-pr:
    # yamllint disable-line rule:line-length
    uses: lgtm-hq/lgtm-ci/.github/workflows/reusable-release-version-pr.yml@f469f4d5c187f0700ccec4c023152fb68ee3dc89 # v0.32.3
    with:
      ecosystems: python
      auto-merge: true
      max-bump: minor
      tooling-ref: 'f469f4d5c187f0700ccec4c023152fb68ee3dc89' # v0.32.3
      egress-policy: block
      egress-preset: pypi
    secrets:
      RELEASE_APP_ID: ${{ secrets.RELEASE_APP_ID }}
      RELEASE_APP_PRIVATE_KEY: ${{ secrets.RELEASE_APP_PRIVATE_KEY }}
    permissions:
      contents: write
      pull-requests: write
