# SPDX-License-Identifier: MIT
# For license details, see the repository root LICENSE file.
---
name: Security - SBOM Generation

'on':
  push:
    branches: [main]
  workflow_dispatch:

permissions: {}

concurrency:
  group: sbom-main-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  sbom:
    # yamllint disable-line rule:line-length
    uses: lgtm-hq/lgtm-ci/.github/workflows/reusable-sbom.yml@f469f4d5c187f0700ccec4c023152fb68ee3dc89 # v0.32.3
    with:
      target: .
      target-type: dir
      sbom-format: cyclonedx-json
      scan-vulnerabilities: true
      create-attestation: true
      tooling-ref: 'f469f4d5c187f0700ccec4c023152fb68ee3dc89' # v0.32.3
      egress-policy: block
      egress-preset: sbom
    permissions:
      contents: read
      security-events: write
      id-token: write
      attestations: write
