# SPDX-License-Identifier: MIT
# For license details, see the repository root LICENSE file.
---
name: Security - OpenSSF Scorecard Analysis

'on':
  schedule:
    - cron: '0 6 * * 1'
  workflow_dispatch:

permissions: {}

concurrency:
  group: scorecards-${{ github.ref }}
  cancel-in-progress: true

jobs:
  scorecards:
    # yamllint disable-line rule:line-length
    uses: lgtm-hq/lgtm-ci/.github/workflows/reusable-scorecards.yml@f469f4d5c187f0700ccec4c023152fb68ee3dc89 # v0.32.3
    with:
      tooling-ref: 'f469f4d5c187f0700ccec4c023152fb68ee3dc89' # v0.32.3
      egress-policy: block
      egress-preset: scorecard
      allowed-endpoints-mode: append
      allowed-endpoints: >
        agent.api.stepsecurity.io:443
        fulcio.sigstore.dev:443
        rekor.sigstore.dev:443
        sigstore.dev:443
        tuf-repo-cdn.sigstore.dev:443
        release-assets.githubusercontent.com:443
        oss-fuzz-build-logs.storage.googleapis.com:443
        ossf.github.io:443
        www.bestpractices.dev:443
    permissions:
      contents: read
      security-events: write
      id-token: write
