# SPDX-License-Identifier: MIT
# For license details, see the repository root LICENSE file.
---
name: Quality Check - Action Pinning Validation

'on':
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - '.github/workflows/**'
      - '.github/actions/**'
  merge_group:
  workflow_dispatch:

permissions: {}

concurrency:
  group: validate-action-pinning-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    # yamllint disable-line rule:line-length
    uses: lgtm-hq/lgtm-ci/.github/workflows/reusable-validate-action-pinning.yml@f8f58587e4c324f6f0c9b3b4f59cfc93aa7d5d0f # v0.69.6
    with:
      tooling-ref: 'f8f58587e4c324f6f0c9b3b4f59cfc93aa7d5d0f' # v0.69.6
      egress-policy: block
      egress-preset: github-tooling
    permissions:
      # read: checkout workflow files for action pinning validation
      contents: read
