# SPDX-License-Identifier: MIT
# For license details, see the repository root LICENSE file.
---
name: Quality Check - Action Pinning Validation

'on':
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - '.github/workflows/**'
      - '.github/actions/**'
  merge_group:
  workflow_dispatch:

permissions: {}

concurrency:
  group: validate-action-pinning-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    # yamllint disable-line rule:line-length
    uses: lgtm-hq/lgtm-ci/.github/workflows/reusable-validate-action-pinning.yml@f469f4d5c187f0700ccec4c023152fb68ee3dc89 # v0.32.3
    with:
      tooling-ref: 'f469f4d5c187f0700ccec4c023152fb68ee3dc89' # v0.32.3
      egress-policy: block
      egress-preset: github-tooling
    permissions:
      contents: read
